from __future__ import annotations

from datetime import datetime
from typing import Any, Protocol

from ..models import (
    Assignment,
    AuditLog,
    Clarification,
    CompilerConfig,
    Contest,
    Discussion,
    JudgeQueueJob,
    JudgeNode,
    OfflinePackRecord,
    Notification,
    Problem,
    ProblemTestData,
    ProblemVersion,
    ProblemSet,
    Submission,
    Tag,
    Team,
    User,
)


class Repository(Protocol):
    """Domain storage contract used by the API layer.

    Runtime storage is supplied by SnapshotRepository, which persists the
    normalized app state through the database layer under apps/api/storage.
    """

    def list_users(self) -> list[User]: ...

    def get_user(self, user_id: str) -> User | None: ...

    def get_user_by_username(self, username: str) -> User | None: ...

    def update_user(self, user: User) -> User: ...

    def list_problems(self) -> list[Problem]: ...

    def get_problem(self, problem_id: str) -> Problem | None: ...

    def add_problem(self, problem: Problem) -> Problem: ...

    def update_problem(self, problem: Problem) -> Problem: ...

    def upsert_problems(
        self,
        problems: list[Problem],
        *,
        version_snapshots: list[tuple[Problem, str, str]] | None = None,
    ) -> list[Problem]: ...

    def delete_problem(self, problem_id: str) -> Problem | None: ...

    def list_problem_versions(self, problem_id: str) -> list[ProblemVersion]: ...

    def get_problem_version(self, problem_id: str, version_id: str) -> ProblemVersion | None: ...

    def add_problem_version(self, problem: Problem, saved_by: str, action: str = "update") -> ProblemVersion: ...

    def restore_problem_version(self, problem_id: str, version_id: str) -> Problem | None: ...

    def get_problem_judge_config(self, problem_id: str) -> dict[str, Any]: ...

    def set_problem_judge_config(self, problem_id: str, judge_config: dict[str, Any]) -> None: ...

    def get_problem_test_data(self, problem_id: str) -> ProblemTestData | None: ...

    def set_problem_test_data(self, metadata: ProblemTestData) -> ProblemTestData: ...

    def list_compiler_configs(self) -> list[CompilerConfig]: ...

    def get_compiler_config(self, code: str) -> CompilerConfig | None: ...

    def update_compiler_config(self, compiler_config: CompilerConfig) -> CompilerConfig: ...

    def list_tags(self) -> list[Tag]: ...

    def get_tag(self, tag_id: str) -> Tag | None: ...

    def add_tag(self, tag: Tag) -> Tag: ...

    def update_tag(self, tag: Tag) -> Tag: ...

    def delete_tag(self, tag_id: str) -> Tag | None: ...

    def list_submissions(self) -> list[Submission]: ...

    def get_submission(self, submission_id: str) -> Submission | None: ...

    def add_submission(self, submission: Submission) -> Submission: ...

    def update_submission(self, submission: Submission) -> Submission: ...

    def delete_submission(self, submission_id: str) -> None: ...

    def list_judge_queue_jobs(self) -> list[JudgeQueueJob]: ...

    def get_judge_queue_job(self, job_id: str) -> JudgeQueueJob | None: ...

    def add_judge_queue_job(self, job: JudgeQueueJob) -> JudgeQueueJob: ...

    def update_judge_queue_job(self, job: JudgeQueueJob) -> JudgeQueueJob: ...

    def delete_judge_queue_job(self, job_id: str) -> None: ...

    def claim_next_judge_queue_job(self, *, node_id: str) -> tuple[JudgeQueueJob, Submission] | None: ...

    def claim_next_code_submission(self, *, worker_id: str, languages: list[str]) -> Submission | None: ...

    def list_contests(self) -> list[Contest]: ...

    def get_contest(self, contest_id: str) -> Contest | None: ...

    def add_contest(self, contest: Contest) -> Contest: ...

    def list_clarifications(self) -> list[Clarification]: ...

    def get_clarification(self, clarification_id: str) -> Clarification | None: ...

    def add_clarification(self, clarification: Clarification) -> Clarification: ...

    def update_clarification(self, clarification: Clarification) -> Clarification: ...

    def list_judge_nodes(self) -> list[JudgeNode]: ...

    def update_judge_node(self, judge_node: JudgeNode) -> JudgeNode: ...

    def list_audit_logs(
        self,
        *,
        actor_id: str | None = None,
        action: str | None = None,
        resource: str | None = None,
        created_from: datetime | None = None,
        created_to: datetime | None = None,
        limit: int = 50,
        offset: int = 0,
    ) -> tuple[list[AuditLog], int]: ...

    def list_problem_sets(self) -> list[ProblemSet]: ...

    def get_problem_set(self, problem_set_id: str) -> ProblemSet | None: ...

    def add_problem_set(self, problem_set: ProblemSet) -> ProblemSet: ...

    def update_problem_set(self, problem_set: ProblemSet) -> ProblemSet: ...

    def list_assignments(self) -> list[Assignment]: ...

    def add_assignment(self, assignment: Assignment) -> Assignment: ...

    def list_teams(self) -> list[Team]: ...

    def add_team(self, team: Team) -> Team: ...

    def list_discussions(self) -> list[Discussion]: ...

    def get_discussion(self, discussion_id: str) -> Discussion | None: ...

    def add_discussion(self, discussion: Discussion) -> Discussion: ...

    def update_discussion(self, discussion: Discussion) -> Discussion: ...

    def list_notifications(self, user_id: str) -> list[Notification]: ...

    def add_notification(self, notification: Notification) -> Notification: ...

    def mark_notification_read(self, notification_id: str, user_id: str) -> Notification | None: ...

    def get_system_config(self) -> dict[str, Any]: ...

    def update_system_config(self, config: dict[str, Any]) -> dict[str, Any]: ...

    def add_audit(
        self,
        actor_id: str | None,
        action: str,
        resource: str,
        metadata: dict[str, Any] | None = None,
    ) -> None: ...

    def list_offline_packs(self) -> list[OfflinePackRecord]: ...

    def get_offline_pack(self, pack_id: str) -> OfflinePackRecord | None: ...

    def add_offline_pack(self, pack: OfflinePackRecord) -> OfflinePackRecord: ...

    def update_offline_pack(self, pack: OfflinePackRecord) -> OfflinePackRecord: ...
